### ISSUE TITLE
Is it singleton?

### ISSUE THREAD

**Issue by MhAllan** [martijn00/XamarinMediaManager#171]
CrossMediaManager.Current means that you can't have more than one instance? how to play two tracks?

**Comment by SimonSimCity** [comment]
Could you please explain your use case? Maybe a solution becomes clearer when you provide more details.

If you think of playing audio only, in a scene, where you have short action-sounds and a background-music (f.e. like within a game ...) I don't know if this implementation is suited for this use-case, because we have quite a couple of handlers, that take the volume down when another player asks for focus and up again after it's finished.

On the other hand, you can just give it a try. Create multiple instances of `IAudioPlayer` and play around with it. But I personally haven't thought of this use-case for this lib until now ...

**Comment by MhAllan** [comment]
I have just seen the code, at first I thought CrossMediaManager.Current is singleton, but now I realized it returns new instance. I think you better rename "Current" to "New", or "Create()".

**Comment by SimonSimCity** [comment]
@MhAllan Yea, but just the first time - then it always returns the instance. It is a singleton approach. But if you really want to get a new instance every time, just call the method `CreateMediaManager()` instead of the property `Current`. https://github.com/martijn00/XamarinMediaManager/blob/develop/MediaManager/CrossMediaManager.cs

**Comment by martijn00** [comment]
What @SimonSimCity says.  It's a singleton approach. `CreateMediaManager` is not public so you can't call it. I guess this is related to https://github.com/martijn00/XamarinMediaManager/issues/100 as well. In general you might want to have multiple MediaPlayers, either to play tracks at the same time, or to pre-buffer so it is faster to play the next track.

**Comment by SantaRita** [comment]
I need to play tow mp3 files and same time, and control every volume file. Is posible ?
