### ISSUE TITLE
How to play local audio file ?

### ISSUE THREAD

**Issue by Srinivasdelta** [martijn00/XamarinMediaManager#291]
I tried to play local audio file with below code:-

 var mediaFile = new MediaFile
            {
                Type = MediaFileType.Audio,
                Availability = ResourceAvailability.Local,
                Url = "sample.mp3",
                ExtractMetadata = true
            };
            await CrossMediaManager.Current.Play(mediaFile);

--> But the file is not playing --> Audio file presented at "Assets" folder under android. Plz help.

**Comment by ragnarek81997** [comment]
i use native solution (Android):
```
Task.Run(async () => {
ViewModel.Queue.Clear();
var rootDirectory = Environment.GetExternalStoragePublicDirectory(string.Empty).AbsolutePath;
var mediaUrl = Path.Combine(rootDirectory, "sample.mp3");
ViewModel.Queue.Add(new MediaFile(mediaUrl, Plugin.MediaManager.Abstractions.Enums.MediaFileType.Audio, Plugin.MediaManager.Abstractions.Enums.ResourceAvailability.Local));
ViewModel.Queue.Repeat = RepeatType.RepeatAll;
await ViewModel.MediaPlayer.Play(ViewModel.CurrentTrack);
});
```

**Comment by danielwebstep** [comment]
Hi @Srinivasdelta ,

how I've done it (for now). I send a video url to the Xamarin Forms component via a Xamarin.iOS/Xamarin.Android native controller/activity.

iOS:

1. Make a folder in the root folder in which your video file should go (ex: Video)
2. Add the video file to that folder (ex: VideoFile.mp4) and set the property to "BundleResource"

In the iOS controller that is connected to the forms controller:

I have defined a property _formsMediaManager which is linking to the forms page/media player that has two methods: "PlayVideo" and "AddToVideoQueue"

var videoPath = Path.Combine(NSBundle.MainBundle.BundlePath, "Video/VideoFile.mp4");
var videoUrl = new NSUrl(videoPath, false);

_formsMediaManager.PlayVideo(videoPath.AbsoluteString); (this method may call to CrossMediaManager.Current.Play(videoUrl);)
or if you want to add to a queue, you can make a method to do so:
_formsMediaManager.AddToVideoQueue(videoPath.AbsoluteString); (this method may call to CrossMediaManager.Current.MediaQueue.Add(...);)

Android:

I have chosen to add the mediafile to the Resources/raw folder:

1. Add the video file to the Resources/raw folder (ex: VideoFile.mp4) and set the property to "AndroidResource"

In the Android activity that is connected to the forms controller:

I have defined a property _formsMediaManager which is linking to the forms page/media player that has two methods: "PlayVideo" and "AddToVideoQueue"

var videoUrl = "android.resource://" + Resources.GetResourcePackageName(Resource.Raw.VideoFile.mp4) + "/" + Resource.Raw.VideoFile;

_formsMediaManager.PlayVideo(videoUrl .AbsoluteString); (this method may call to CrossMediaManager.Current.Play(videoUrl);)
or if you want to add to a queue, you can make a method to do so:
_formsMediaManager.AddToVideoQueue(videoUrl ); (this method may call to CrossMediaManager.Current.MediaQueue.Add(...);)

**Comment by speaker** [comment]
There seems to be at least one error in the code, and I can't make it work even after fixing it.
The line that contains:
**...Resources.GetResourcePackageName(Resource.Raw.VideoFile.mp4)...**
can't be correct. **Resource.Raw.VideoFile.mp4** yields: **'int' does not contain a definition for 'mp4' and no accessible extension method 'mp4' accepting a first argument of type 'int' could be found (are you missing a using directive or an assembly reference?)**
Also, Is it really the intent to use the descriptor value in the path? 
**var videoUrl = "android.resource://" + Resources.GetResourcePackageName(Resource.Raw.VideoFile.mp4) + "/" + Resource.Raw.VideoFile;**
is creting a path like **android.resource://com.program.myapp/39782463874** should it be **android.resource://com.program.myapp/VideoFile.mp4**?

Even when fixed by removing **.mp4** from the **GetResourcePackageName() call**, I cannot get a path that will successfully resolve. I've tried the version with the integer value, as well as with and without the ".mp4" as a suffic to the file name.

I am testing the path with a call: **Java.IO.File file= new Java.IO.File(fn); return file.Exists();**

Am I missing something?

**Comment by jrahma** [comment]
How to Play audio from local Resources using Xamarin Forms?
