### ISSUE TITLE
Couldn't open http://streamip:port/: java.io.FileNotFoundException:

### ISSUE THREAD

**Issue by SoftwareMagicIT** [martijn00/XamarinMediaManager#393]
Work fine on iOS In Android Kit Kat emulator work fine. But in nougat too time for starting and in debugger console appear: Couldn't open http://address:port/: java.io.FileNotFoundException:

MediaFile is setting as remote uri

**Comment by fabcal24** [comment]
Currently I need to release app and I made little code for workaround with native platform's players and bidirectional communication from native to cross and vice versa. After summertime I think to see and solve bugs. Cuurently my trouble is I can't install Tizen SDK because I don't have space on my ssd of developer workstation, and i can't recompile after changes
