### ISSUE TITLE
Xamarin Forms Android Notifications not working

### ISSUE THREAD

**Issue by mcjaal111** [martijn00/XamarinMediaManager#421]
In Xamarin Forms Android the lines that I use to play and start notifications.
`  private async void PlayAudio_OnClicked(object sender, EventArgs e)
        {
            var mediaFile = new MediaFile
            {
                Type = MediaFileType.Audio,
                Availability = ResourceAvailability.Remote,
                Url = "https://audioboom.com/posts/5766044-follow-up-305.mp3",
                MetadataExtracted = true
            };
            await CrossMediaManager.Current.Play(mediaFile);
            CrossMediaManager.Current.MediaNotificationManager?.StartNotification(mediaFile);
            CrossMediaManager.Current.MediaNotificationManager?.UpdateNotifications(mediaFile, MediaPlayerStatus.Playing);
        }`

This is the callstack
![image](https://user-images.githubusercontent.com/47902748/53271777-46b03400-36a4-11e9-8b9d-c015b208422b.png)

In Xamarin Forms IOS I don't have problems with notifications, works perfectly.

### Expected behavior :thinking:
Play MP3 and start player notifications

### Actual behavior :bug:
just play the mp3 but notifications doesn't start.

Also I got this message too, I don't know if this might be the problem
![image](https://user-images.githubusercontent.com/47902748/53271691-0f418780-36a4-11e9-8e87-2dbb2c799c36.png)

Thank you.
### Configuration :wrench:

**Version:** 2.x

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [X ] :monkey: Xamarin.Forms 3.5.0.16.9047

**Comment by valentin-debris** [comment]
Hi,

I had the same issue. After a little search, the problem with this repo is that the code here is not the same in the Nuget (the nuget was release in 2017, and a lot of stuff here have been added later). Until the futur release, you can try the unofficial MediaManager (https://www.nuget.org/packages/MediaManager.Unofficial/) which is just a fork of the current repo with somes fix to generate the nuget.

Also, if you use Android API >= 26, you HAVE TO define a channel for the notification, otherwise it will not be visible. Sadly, this functionality is not in this nuget (neither in the unofficial), so you will have to develop a custom code for Android to create the notification.

Regards,
Valentin

**Comment by mcjaal111** [comment]
Hi, 

Thank you Valentin, I really appreciate it. I should better start developing a custom code for Android. Maybe that's better from the beginning and not trying to find something for Xamarin Forms.

Regards, 
Mirna
