### ISSUE TITLE
CrossMediaManager.Current.Init(this)  <- not available 

### ISSUE THREAD

**Issue by RichardSV15** [martijn00/XamarinMediaManager#451]
### Old (and correct) behavior
Project loaded correctly

### Current behavior
I'm using xamarin forms for IOS and Android . I get the following when trying to build or run any CrossMediaManager methods on android. I have uninstalled the plugin and reinstalled it again and it still doesn't work.  Also i can't initialize android using the Init(this) method because it says Init() has no overload method 'init' takes one argument.  It still does not initialize properly even if i use "CrossMediaManager.Current.Init();" 

This functionality is not implemented in the portable version of this assembly. You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.

### Reproduction steps
Update from 0.4.5 to .0.5.+

### Configuration

**Version:** 1.x

**Platform:** 
- [x] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by valentin-debris** [comment]
@RichardSV15 

This is not a regression but a wrong config for your project. It has been reported in #443 and solved. Please, use it to solve your problem (also in #437 )

**Comment by RichardSV15** [comment]
@valentin-debris 

Thank you so much for such fast reply. 

solved my problem by setting target to Android Pie API 28 and rebuilding project.

I'm sorry this had been covered before. Tried my best to look for it but i didn't get to find the solution myself.

**Comment by jaimestuardo** [comment]
So, the only solution is to target Pie 28? I have tried to solve this by targetting Pie 28 in both "Compile using Android version (Target Framework)" and in "Target Android Version". When I did that, the project did not even compile with a very cryptic error.

I should return to API 27.

Is there a way to use this using API 27?

Regards

Jaime

**Comment by martijn00** [comment]
@jaimestuardo See the readme: https://github.com/martijn00/XamarinMediaManager#important

You need to set api to 28 and set the dex tools to d8.

**Comment by jaimestuardo** [comment]
@martijn00 I have set Target Android Version to API Level 28 and Minimum Android Version to API Level 21. Even that way, I got the same error. 

The github readme says this:

> ExoPlayer 2.9.6 and higher use Java 8. You need to set the Dex tool to D8 <AndroidDexTool>d8</AndroidDexTool>

I found that I can set Dex compiler to d8. Is the same as Dex tool? I have set to d8.

The I compiled and tun and the same error happens.

However, something took my attention. I have seen the source code for CrossMediaManager and I saw this:

`static IMediaManager CreateMediaManager()
        {
#if NETSTANDARD
            return null;
#else
#pragma warning disable IDE0022 // Use expression body for methods
            return new MediaManagerImplementation();
#pragma warning restore IDE0022 // Use expression body for methods
#endif
        }`

When using NET Standard, null is returned for CrossMediaManager.Current. That is why I am receiving the exception.

I added MediaManager in both the shared project and the Android project. The shared project has target framework NET Standard 2.0. The Android project does not have such a configuration.

I have downloaded the Github project to reference the project instead of NuGet but it does not even compile.

Any further help, please?

Regards

Jaime

**Comment by mknotzer** [comment]
not working with d8 & API 28, CrossMediaManager.Current.Init(this) not available

**Comment by arjung5** [comment]
Solution is you have to change The andriod Version in Andriod->Properties->Application
![solution](https://user-images.githubusercontent.com/63615811/107843993-cbe30500-6df5-11eb-8d91-f694d501a192.png)
