### ISSUE TITLE
Exoplayer2 only supports API24+? 

### ISSUE THREAD

**Issue by jamesmontemagno** [martijn00/XamarinMediaManager#524]
## 💬 Questions and Help

When i have my min-sdk set to 21 I try to run it and get an error when i try to deploy saying that exoplayer2 requires API24... is this correct? If so, can we update the readme?

**Comment by jamesmontemagno** [comment]
This may be a bug because I set it to 24 and still get:

Severity	Code	Description	Project	File	Line	Suppression State
Error		java/lang/Object;I)V: defining a default interface method requires --min-sdk-version >= 24 (currently 13) for interface methods: com.google.android.exoplayer2.Player$EventListener.onTimelineChanged : (Lcom/google/android/exoplayer2/Timeline;Ljava/lang/Object;I)V	Hanselman.Android

**Comment by martijn00** [comment]
You need to set the dex tools to d8 otherwise it gives weird errors like this. There is a section in the readme about it but it might not be super clear.

**Comment by jamesmontemagno** [comment]
GOTCHA! Will try that :) Pictures would be good.

**Comment by martijn00** [comment]
<img width="804" alt="Screenshot 2019-07-07 at 16 53 36" src="https://user-images.githubusercontent.com/6221156/60795029-3daf9300-a16b-11e9-917d-b6b2ae3edf7d.png">

This is how mine looks like.

**Comment by cklenk** [comment]
Thank you for this clarification! I had the same issue :D

**Comment by CDBridger** [comment]
I have the same issue but setting d8 then creates a new issue, which is "Compilation can't be completed because some library classes are missing"

`>R8 : warning : Missing class: com.samsung.android.fingerprint.FingerprintManager$EnrollFinishListener
1>R8 : warning : Missing class: com.samsung.android.fingerprint.FingerprintIdentifyDialog$FingerprintListener
1>R8 : warning : Missing class: com.samsung.android.fingerprint.IFingerprintClient$Stub
1>R8 : error : Compilation can't be completed because some library classes are missing.
1>  Compilation failed`
