### ISSUE TITLE
Custom notifications

### ISSUE THREAD

**Issue by pinewoodranger** [martijn00/XamarinMediaManager#606]
Hello,

I'm trying to do a custom implementation of notifications to control the player. I cant seem to find any explanation on how to do this. Can anyone point me in the right direction for say, adding a button to the notification. 

The previous issues posted here are all outdated and don't reflect the current code base.

-------------
In the grand scheme, I'm adding multiple files to the player queue but some of the songs added don't necessarily hold a media source uri. Catching the songs before they play and fetching the uri (which can take a few seconds) was my first go to but the player notification just hangs and becomes unresponsive. So now I'll be adding only one song at a time and have my own playlist instead of the builtin queue but I'd have to add next&previous song buttons on the notification - thus the question.

**Comment by XXcharlosXX** [comment]
Did you figure out the solution?

**Comment by pinewoodranger** [comment]
> Did you figure out the solution?

No. In the end I decided on going with my own media player. My use cases are pretty specific here and XamarinMediaManager is not fit to handle them.

**Comment by martijn00** [comment]
@pinewoodranger can you tell what those use cases are? Maybe i can put them on the backlog.

**Comment by XXcharlosXX** [comment]
@martijn00 I was utilizing the MediaManager plugin for a radio app for the Company I work for.
Unfortunately, ever since Android 8 and the implementation of DOZE the player will stop after 1 minute of going into the background without being plugged in.
KEY WORD: PLUGGED IN.
The player can play for years when the device is charging, but when it is not charging DOZE takes over and removes any wakelocks and wifilocks.

This is very frustrating. I have to fix the issue so I too have started created my own custom implementation of an Android 8+ player.
Anyways, just thought i'd let you know since you're active on this thread?


P.S. - As per customizing the notifications. I'd really like to have the ability to enable which buttons are used. (Radio stream can only STOP and PLAY, no need for seek or next or pause.)
Also being able to edit the title and update the title as the song changes on stream would be nice.

**Comment by martijn00** [comment]
Customize like you want is already possible: https://github.com/martijn00/XamarinMediaManager/blob/develop/MediaManager/Notifications/INotificationManager.cs#L9

Set that to false, and it will only show play, pause and stop.

The title is set based on the IMediaItem properties, just update them on the fly and call https://github.com/martijn00/XamarinMediaManager/blob/develop/MediaManager/Notifications/INotificationManager.cs#L11

For me it continues playing after 1 min. What device are you using, because i think some vendors are more restrictive.

**Comment by XXcharlosXX** [comment]
I am using the Google Pixel. I have consistently reproduced the issue on the Pixel and the Pixel 3 both running Android 10.

**Comment by XXcharlosXX** [comment]
I noticed some things changed in this project lately.
Notifications are now unable to be disabled.
I am guessing you created a foreground service to prevent DOZE from shutting releasing the wakelocks and what not.

**Comment by Jack-Paul** [comment]
I also have a use case similar to @pinewoodranger , where I won't add every song in the inbuilt queue, instead,  when ever the media item is finished, I will update the next song from my side code, so now the control in the notifications doesn't work, I just need any callback event when notification next or previous button is clicked, so @martijn00  can you please tell me is there any way to do this?

thanks...
