### ISSUE TITLE
MediaForms.UWP sample does not build

### ISSUE THREAD

**Issue by nudaca** [martijn00/XamarinMediaManager#81]
The UWP Forms sample does not build.
Here is the build output:
```
1>------ Build started: Project: Plugin.MediaManager.Forms.UWP, Configuration: Debug x86 ------
1>  Plugin.MediaManager.Forms.UWP -> C:\Users\ndc\Source\Repos\XamarinMediaManager\MediaManager\Plugin.MediaManager.Forms\Plugin.MediaManager.Forms.UWP\bin\x86\Debug\Plugin.MediaManager.Forms.UWP.dll
2>------ Build started: Project: MediaForms.UWP, Configuration: Debug x86 ------
2>  MediaForms.UWP -> C:\Users\ndc\Source\Repos\XamarinMediaManager\Samples\Forms\MediaForms.UWP\bin\x86\Debug\MediaForms.UWP.exe
2>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AppxPackage\Microsoft.AppXPackage.Targets(1692,5): error APPX1101: Payload contains two or more files with the same destination path 'Plugin.MediaManager.pdb'. Source files: 
2>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AppxPackage\Microsoft.AppXPackage.Targets(1692,5): error APPX1101: C:\Users\ndc\Source\Repos\XamarinMediaManager\MediaManager\Plugin.MediaManager\bin\Debug\Plugin.MediaManager.pdb
2>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AppxPackage\Microsoft.AppXPackage.Targets(1692,5): error APPX1101: C:\Users\ndc\Source\Repos\XamarinMediaManager\MediaManager\Plugin.MediaManager.UWP\bin\x86\Debug\Plugin.MediaManager.pdb
3>------ Skipped Deploy: Project: MediaForms.UWP, Configuration: Debug x86 ------
3>Project not selected to build for this solution configuration 
========== Build: 1 succeeded, 1 failed, 5 up-to-date, 0 skipped ==========
```

**Comment by RobTillie** [comment]
Does anyone have an update on this? I immediately ran into this when cloning dev and trying to build it in VS 2017.
The problem seems to be that both Plugin.MediaManager and Plugin.MediaManager.UWP result in an assembly called Plugin.MediaManager. Could someone explain why this is and how we can build it?

**Comment by martijn00** [comment]
We use bait and switch to load the platform specific assembly instead of the pcl one. That is why the assembly name is the same. Maybe the output path should be changed to fix this for some people.

**Comment by RobTillie** [comment]
Thanks for the explanation, I wasn't aware of the bait-and-switch trick for plugins. 
The issue does not appear to be a MediaManager bug, but a bug in the build system, it has been reported in numerous places:
[https://github.com/jamesmontemagno/Xamarin-Templates/issues/8](https://github.com/jamesmontemagno/Xamarin-Templates/issues/8)
[http://www.poz1.com/baitswitch/](http://www.poz1.com/baitswitch/)
[https://bugzilla.xamarin.com/show_bug.cgi?id=44640](https://bugzilla.xamarin.com/show_bug.cgi?id=44640)

No one seems to be actually fixing the problem. A suggested fix is to reference the dll directly instead of the project, but in this case that does not seem work because MediaForms.UWP references Plugin.MediaManager indirectly through the MediaForms project.

I have no idea if this can be fixed at all. .NET Standard cannot come soon enough.

**Comment by myrobotzone** [comment]
I was able to fix this, for details checkout the following fork: https://github.com/myrobotzone/XamarinMediaManager. I will create a pull request.

**Comment by martijn00** [comment]
Fixed
